services:
  qwen-tts-web:
    image: cadretail/qwen-tts:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qwen-tts-web
    restart: unless-stopped

    ports:
      - "7811:7811"

    gpus: all

    volumes:
      - ./app/outputs:/app/app/outputs
      - ./app/uploads:/app/app/uploads
      - ~/.cache/huggingface:/root/.cache/huggingface

    environment:
      USE_MOCK_TTS: "false"

      QWEN_TTS_DEVICE: "cuda:0"
      QWEN_TTS_DTYPE: "bfloat16"
      QWEN_TTS_FLASH_ATTENTION: "false"
      QWEN_TTS_MODEL: "Qwen/Qwen3-TTS-12Hz-1.7B-VoiceDesign"

      HF_HOME: "/root/.cache/huggingface"